site_name: Book Recommendation System Documentation
nav:
  - Home: index.md
  - User Guide: installation.md
  - DB Schema: db_schema.md
  - API Documentation: api.md
  - Using Your Own Data: own_data.md
  - Recommendation Model: recommendation_model.md
  - SQL Interactions: sql_interactions.md

theme:
  name: material

plugins:
  - mkdocstrings
