site_name: Book Recommendation

nav: 
    - Home: index.md
    - Getting Started: getting_started.md
    - Database Schema: db_schema.md
    - SQL Interactions: sql_interactions.md
    - Recommendation Model: recommendation_model.md
    - API: api.md
    - Additional: additional.md

theme:
  name: material

plugins:
- mkdocstrings: 
    handlers: 
      python: 
        options: 
          heading_level: 3
          show_root_heading: true
