site_name: Book Recommendation

nav: 
    - Home: index.md
    - Getting Started: getting_started.md
    - Database Schema: db_schema.md
    - SQL Interactions & Functions: sql_interactions.md
    - Recommendation Model: recommendation_model.md
    - API: api.md
    - Additional: additional.md

theme:
  name: material
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to system preference

plugins:
- search
- mkdocstrings: 
    handlers: 
      python: 
        options: 
          heading_level: 3
          show_root_heading: true
